openapi: 3.0.0
info:
  title: vaccine-API
  version: 1.0.0
servers:
  - url: http://{{host}}
  - url: http://{{https_host}}
  - url: http://{{local}}
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Citizens
  - name: HealthFacilitators
  - name: Family
  - name: Booking Session API
paths:
  /api/v1/citizen/logins:
    post:
      tags:
        - Citizens
      summary: Citizens Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: bajanrdana23@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/citizen/profiles:
    get:
      tags:
        - Citizens
      summary: CitizenFindById Copy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/citizen/sessions:
    get:
      tags:
        - Citizens
      summary: Get Citizen And Family SESSION Copy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/citizen/registers:
    post:
      tags:
        - Citizens
      summary: CitizenRegister
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: bajanrdana23@gmail.com
                password: '123456'
                name: agus janardana
                birthday: '2021-12-27T10:31:58Z'
                NIK: '123124'
                handphone_number: '123123'
                age: 12
                gender: Male
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/citizens:
    put:
      tags:
        - Citizens
      summary: Update Citizen
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                birthday: '2021-11-27T10:31:58Z'
                address: jalan
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/citizen/profile/{id}:
    get:
      tags:
        - Citizens
      summary: CitizenFindById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id citizennya
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/registers:
    post:
      tags:
        - HealthFacilitators
      summary: Register Health Facilitators
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                facilitator_name: test
                email: test3@gmail.com
                password: test123password
                address: here is address
                longitude: 123123asde
                latitude: a123asd
                type: rumah sakit
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/logins:
    post:
      tags:
        - HealthFacilitators
      summary: Login Health Facilitators
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: test2@gmail.com
                password: test123password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admins:
    get:
      tags:
        - HealthFacilitators
      summary: Get All HF & detail
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/{id}:
    get:
      tags:
        - HealthFacilitators
      summary: Health Facilitator Find By ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id health facilitatorsnya
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - HealthFacilitators
      summary: Update HealthFacilitators
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                facilitator_name: TESTEDIT
                facilitators_certification: TESTEDIT
                address: TESTEDIT
                longitude: TESTEDIT
                latitude: TESTEDIT
                type: TESTEDIT
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: ID ini adalah ID ADMIN
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/family/{id}:
    put:
      tags:
        - HealthFacilitators
      summary: Update Family Member By HF ( Gunakan di menu Health Facilitators !!! )
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status_vaccines: DOSIS 1
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id family members
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/families/1:
    get:
      tags:
        - Family
      summary: Get Family by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/family/citizens:
    get:
      tags:
        - Family
      summary: get family owned by a citizen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/families:
    post:
      tags:
        - Family
      summary: Create Family
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Juna ID 3
                birthday: '2021-12-27T10:31:58Z'
                nik: '12123123'
                age: 15
                handphone: '087762827666'
                gender: Male
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/families/{id}:
    put:
      tags:
        - Family
      summary: Update Family By Id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: JunaEDIT
                birthday: '2021-12-27T10:31:58Z'
                nik: '12123123'
                age: 15
                handphone: '087762827666'
                gender: Male
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/families/3:
    delete:
      tags:
        - Family
      summary: Delete a Family Members
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccines:
    post:
      tags:
        - CRUD vaccine ( need login as HF )
      summary: Create Vaccine ( LOGIN AS HF FIRST )
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Sinovac2
                stock: 50
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccine/{id}:
    get:
      tags:
        - CRUD vaccine ( need login as HF )
      summary: Find Vaccine by Id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - CRUD vaccine ( need login as HF )
      summary: Edit Vaccine by ID ( LOGIN AS HF FIRST )
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: SinovacEDIT
                stock: 200
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - CRUD vaccine ( need login as HF )
      summary: Delete Vaccine by ID ( LOGIN AS HF FIRST )
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccines/1:
    get:
      tags:
        - CRUD vaccine ( need login as HF )
      summary: Find Vaccine Owned By HF ( LOGIN HF FIRST !)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccine/sessions:
    post:
      tags:
        - CRUD session ( login as HF first)
      summary: Create Vaccine Session ( Login as HF first) Copy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                start_date: '2021-11-27T10:31:58Z'
                end_date: '2021-11-27T10:31:58Z'
                quota: 40
                session_type: SESI 1
                vaccine_id: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - CRUD session ( login as HF first)
      summary: Get All Vaccine Sessions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccine/session/{id}:
    get:
      tags:
        - CRUD session ( login as HF first)
      summary: Get Session By ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '8'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - CRUD session ( login as HF first)
      summary: Delete Session By Id (login to owner HF)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id session
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - CRUD session ( login as HF first)
      summary: Edit Session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                start_date: '2021-11-27T10:31:58Z'
                end_date: '2021-11-27T10:31:58Z'
                quota: 200
                session_type: SESI 1
                vaccine_id: 1
                status: UNAVAILABLE
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id session
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vaccine/session/owned/{id}:
    get:
      tags:
        - CRUD session ( login as HF first)
      summary: Get Session Owned By HF
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id health facilitatornya
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/session/bookings/{id}:
    post:
      tags:
        - Booking Session API
      summary: Citizen Booking Session
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: ID SESSIONNYA
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/session/family/8:
    get:
      tags:
        - Booking Session API
      summary: Get Session Detail by Family Id
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/session/detail/{id}:
    get:
      tags:
        - Booking Session API
      summary: Get Session Detail By Detail Id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: id ini adalah id session detail nya
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/session/{id}:
    get:
      tags:
        - Booking Session API
      summary: Get Detail by Session ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: ID ini adalah ID sessionnya
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}